### ISSUE TITLE
Problème d'affichage sur un grand nombre de noeuds/liens

### ISSUE THREAD

**Issue by ferdbold** [terra-arcana/terra-arcana#112]
![screen shot 2016-04-25 at 4 56 47 pm](https://cloud.githubusercontent.com/assets/2939098/14798655/b2c21180-0b06-11e6-9baf-984a6d7ac55c.png)

**Comment by ferdbold** [comment]
J'ai trouvé la source du bug: après que le zodiaque dépasse 1000 éléments, la console PHP écrit cet avertissement:
`PHP Warning:  Unknown: Input variables exceeded 1000. To increase the limit change max_input_vars in php.ini. in Unknown on line 0`

@FChapeau Il faudrait inclure au build Docker la création d'un `php.ini` personnalisé dans lequel cette valeur serait augmentée à 5000.

**Comment by FChapeau** [comment]
Je regarde ça en ce moment.
