### ISSUE TITLE
Permettre à des compétences de ne pas avoir de signe

### ISSUE THREAD

**Issue by ferdbold** [terra-arcana/terra-arcana#116]
Les compétences telles que Porteur du Destin, Endurance, Méditation et Immersion ne font pas partie d'un Signe, mais ce n'est pas possible actuellement.

**Comment by Macker28** [comment]
On peut créer un nouveau Signe = Priorème. Solution temporaire.

**Comment by ferdbold** [comment]
Possible. Quoique on s'en fout un peu présentement vu que le signe ne sert qu'à l'affichage des détails d'une compétence. Le calcul du signe d'un personnage ne se fait même pas encore. C'est quand même assez bas dans les priorités comme problème

**Comment by ferdbold** [comment]
Ça va rester comme ça, car ça va donner le titre "Priorème [peuple]" aux nouveaux personnages dans le Zodiaque.
